name: CI Build

on:
  push:
    branches: [ master, ci_test ]
  pull_request:
    branches: [ master ]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.8.0
        with:
          version: '5.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2013_64'
          extra: '--external 7z'
    
      - name: Fetch JamTaba static library dependencies
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/s/qckwsmaqlditwpb/JamTaba-static-libs.zip?dl=1" -OutFile JamTaba-static-libs.zip
          mkdir $env:GITHUB_WORKSPACE\JamTaba\libs
          Expand-Archive -Force -Path JamTaba-static-libs.zip -DestinationPath $env:GITHUB_WORKSPACE\JamTaba\libs

      - name: Fetch VST SDK
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/s/9lxowvn7k3bfkf1/VST_SDK.zip?dl=1" -OutFile VST_SDK.zip
          mkdir $env:GITHUB_WORKSPACE\JamTaba\VST_SDK
          Expand-Archive -Force -Path VST_SDK.zip -DestinationPath $env:GITHUB_WORKSPACE\JamTaba\VST_SDK
          
      - name: Build Standalone Windows
        run: |
          cd $env:GITHUB_WORKSPACE\JamTaba\PROJECTS\Standalone
          qmake.exe Standalone.pro -r -spec win32-g++ CONFIG=release
          make

